create table mcc_mnc_oper_list (id integer primary key, country char(3), mcc integer, mnc char(3), oper char(45) );
create unique index uniq_idx on mcc_mnc_oper_list(mcc, mnc);
BEGIN;
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AAA", 901, "15", "OnAir");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AAM", 901, "12", "Maritime Communications Partner AS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ABW", 363, "20", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ABW", 363, "01", "SETAR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AFG", 412, "01", "AF AWCC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AFG", 412, "50", "Etisalat Af");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AFG", 412, "40", "MTN AF");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AFG", 412, "20", "ROSHAN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AGO", 631, "02", "UNITEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AIA", 365, "840", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ALB", 276, "01", "A M C");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ALB", 276, "03", "EAGLE AL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ALB", 276, "04", "PLUS AL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ALB", 276, "02", "Vodafone AL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AND", 213, "03", "MOBILAND");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ANT", 362, "69", "Digicel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ANT", 362, "91", "CHIPPIE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ANT", 362, "51", "Telcell GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ANT", 362, "78", "Kla");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARE", 424, "03", "du");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARE", 424, "02", "ETISALAT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARG", 722, "310", "CLARO ARGENTINA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARG", 722, "341", "AR PERSONAL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARG", 722, "010", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARG", 722, "07", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARM", 283, "01", "Beeline AM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARM", 283, "05", "MTS ARM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ARM", 283, "10", "Orange AM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ASM", 544, "110", "Bluesky Communications");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ATG", 344, "030", "APUA imobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ATG", 344, "930", "Cingular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ATG", 344, "920", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUS", 505, "02", "YES OPTUS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUS", 505, "01", "Telstra Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUS", 505, "06", "3TELSTRA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUS", 505, "03", "vodafone AU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUT", 232, "01", "A1");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUT", 232, "12", "yesss!");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUT", 232, "10", "3 AT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUT", 232, "05", "3 AT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUT", 232, "03", "T-Mobile A");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AUT", 232, "07", "telering");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AZE", 400, "01", "AZE - AZERCELL GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AZE", 400, "04", "AZ Nar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("AZE", 400, "02", "BAKCELL AZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BDI", 642, "02", "BDI TEMPO-AFRICELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BDI", 642, "01", "BDI ECONET");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BDI", 642, "07", "SMART");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BDI", 642, "03", "ONATEL BDI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BDI", 642, "82", "TELECEL-BDI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEL", 206, "01", "BEL PROXIMUS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEL", 206, "20", "BASE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEL", 206, "10", "B mobistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEN", 616, "04", "BELL BENIN COMMUNICATION");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEN", 616, "02", "ETISALAT BENIN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEN", 616, "05", "GloBenin");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BEN", 616, "03", "MTN BENIN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BFA", 613, "02", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGD", 470, "07", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGD", 470, "03", "Banglalink");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGD", 470, "01", "Grameenphone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGD", 470, "00", "BGD ROBI AXIATA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGD", 470, "04", "BGD bMobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGR", 284, "03", "Vivacom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGR", 284, "05", "Telenor BG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BGR", 284, "01", "Mtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BHR", 426, "01", "BATELCO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BHR", 426, "04", "VIVA BH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BHR", 426, "02", "Zain BH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BHS", 364, "39", "BTC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BIH", 218, "90", "BH Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BIH", 219, "01", "HT HR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BIH", 218, "05", "m:tel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BLR", 257, "02", "MTS BY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BLR", 257, "01", "BY VELCOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BLZ", 702, "67", "BTL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BMU", 350, "000", "CELLONE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BMU", 350, "010", "Cingular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BOL", 736, "02", "BOMOV");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BOL", 736, "01", "VIVA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BOL", 736, "03", "TIGO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "32", "Algar Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "33", "Algar Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "34", "Algar Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "05", "Claro");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "39", "Nextel Brasil");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "31", "Oi");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "16", "Oi");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "24", "Oi");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "15", "BRA SCTL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "03", "TIM BRASIL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "04", "TIM BRASIL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "02", "TIM BRASIL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "23", "VIVO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "11", "VIVO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "06", "VIVO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRA", 724, "10", "VIVO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRB", 342, "600", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRB", 342, "750", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRN", 528, "11", "BRU-DSTCom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BRN", 528, "02", "PCSB");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BTN", 402, "11", "BT B-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BTN", 402, "77", "TASHICELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BWA", 652, "04", "beMOBILE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BWA", 652, "01", "BW MASCOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("BWA", 652, "02", "Orange");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAF", 623, "01", "ETISALAT RCA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAF", 623, "04", "NationLink");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAF", 623, "02", "Telecel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "610", "Bell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "270", "Eastlink");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "320", "Mobilicity");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "340", "Execulink Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "660", "MTS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "370", "Fido");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "720", "Rogers Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "780", "SaskTel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "220", "TELUS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "880", "FastRoam");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "490", "WIND");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CAN", 302, "940", "Wightman");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHE", 228, "03", "Orange CH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHE", 228, "02", "Sunrise");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHE", 228, "01", "Swisscom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "03", "CLARO CHL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "01", "ENTEL PCS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "10", "ENTEL PCS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "09", "Nextel 3G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "02", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "07", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHL", 730, "08", "CHL VTR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHN", 460, "00", "CHINA MOBILE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHN", 460, "11", "CHN-CT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHN", 460, "01", "CHN-UNICOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CHN", 460, "09", "CHN-UNICOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CIV", 612, "02", "ETISALAT CI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CIV", 612, "04", "KoZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CIV", 612, "05", "MTN CI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CIV", 612, "03", "Orange CI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CMR", 624, "01", "MTN CAM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CMR", 624, "02", "Orange CAM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CMR", 624, "04", "Nexttel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COD", 630, "02", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COD", 630, "90", "Africell RDC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COD", 630, "86", "Orange RDC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COD", 630, "89", "TIGO DRC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COD", 630, "01", "Vodacom Congo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COD", 630, "88", "CD Smart");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COG", 629, "01", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COG", 629, "02", "AZUR COG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COG", 629, "10", "COG MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COG", 629, "07", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COK", 548, "01", "CK KOKANET");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COL", 732, "103", "COL MOV / TIGO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COL", 732, "111", "COL MOV / TIGO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COL", 732, "101", "Claro");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COL", 732, "187", "ETB 4G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COL", 732, "123", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("COM", 654, "01", "HURI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CPV", 625, "02", "UNITELT+");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CRI", 712, "03", "CLARO CR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CRI", 712, "02", "I.C.E.");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CRI", 712, "01", "I.C.E.");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CRI", 712, "04", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CUB", 368, "01", "CUBACEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CYM", 346, "140", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CYP", 280, "01", "Cyta-Voda");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CYP", 280, "10", "MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CZE", 230, "02", "O2 CZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CZE", 230, "01", "T-Mobile CZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("CZE", 230, "03", "Vodafone CZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DEU", 262, "03", "E-Plus");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DEU", 262, "07", "o2 – de");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DEU", 262, "08", "o2 – de");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DEU", 262, "01", "Telekom.de");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DEU", 262, "02", "Vodafone.de");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DJI", 638, "01", "DJ EVATIS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DMA", 366, "110", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DMA", 366, "020", "Cingular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DNK", 238, "06", "3 DK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DNK", 238, "01", "DK TDC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DNK", 238, "02", "Telenor DK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DNK", 238, "77", "Telenor DK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DNK", 238, "66", "Telia-Telenor DK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DNK", 238, "20", "Telia DK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DOM", 370, "02", "CLARO DOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DOM", 370, "01", "Orange");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DOM", 370, "04", "VIVA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DZA", 603, "01", "ALG Mobilis");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DZA", 603, "02", "Djezzy");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("DZA", 603, "03", "Ooredoo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ECU", 740, "01", "CLARO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ECU", 740, "02", "CNT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ECU", 740, "00", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("EGY", 602, "01", "EGY MobiNiL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("EGY", 602, "03", "Etisalat");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("EGY", 602, "02", "vodafone EG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ESP", 214, "03", "Orange");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ESP", 214, "07", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ESP", 214, "01", "vodafone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ESP", 214, "04", "YOIGO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("EST", 248, "01", "EMT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("EST", 248, "02", "EE Elisa");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("EST", 248, "03", "Tele2 EE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ETH", 636, "01", "ETH MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FIN", 244, "03", "Fl DNA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FIN", 244, "12", "Fl DNA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FIN", 244, "05", "FI elisa");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FIN", 244, "91", "FI SONERA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FIN", 244, "36", "Sonera - SuomenYV");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FIN", 244, "14", "FI AMT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FJI", 542, "02", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FJI", 542, "01", "FJ VODAFONE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FLK", 750, "001", "Sure FLK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "20", "F-Bouygues Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "88", "F - Contact");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "15", "Free");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 340, "01", "F-Orange");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "01", "Orange F");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "02", "F-Contact");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "09", "F SFR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "10", "F SFR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "13", "F - Contact");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRA", 208, "11", "SFR FEMTO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRO", 288, "01", "Foroya Tele");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FRO", 288, "02", "VODAFONE FO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("FSM", 550, "01", "FSM Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GAB", 628, "02", "ETISALAT GAB");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GAB", 628, "03", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GAB", 628, "01", "LIBERTIS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 901, "14", "AeroMobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "33", "EE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "32", "EE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "30", "EE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "31", "EE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "20", "3 UK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 901, "11", "Inmarsat");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "50", "JT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "58", "Manx Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "28", "Marathon");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "55", "Sure");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "19", "PMN UK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "10", "O2 - UK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GBR", 234, "15", "vodafone UK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GEO", 282, "01", "GEO-GEOCELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GEO", 282, "02", "MAGTI-GSM-GEO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GEO", 282, "04", "BEELINE GE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GHA", 620, "06", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GHA", 620, "02", "GH Vodafone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GHA", 620, "01", "GH MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GIB", 266, "09", "Shine");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GIB", 266, "01", "GIBTEL GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GIN", 611, "04", "GNMTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GIN", 611, "01", "Orange GN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GIN", 611, "02", "GN LAGUI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GLP", 340, "08", "DAUPHIN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GLP", 340, "20", "Digicel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GMB", 607, "02", "AFRICELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GMB", 607, "03", "GM COMIUM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GMB", 607, "01", "GAMCEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GMB", 607, "04", "Qcell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GNB", 632, "02", "MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GNQ", 627, "03", "GNQ-Muni");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GNQ", 627, "01", "GNQ01");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRC", 202, "01", "GR COSMOTE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRC", 202, "05", "vodafone GR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRC", 202, "09", "WIND GR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRC", 202, "10", "WIND GR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRD", 352, "110", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRD", 352, "030", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GRL", 290, "01", "TELE Greenland");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GTM", 704, "02", "Comcel_GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GTM", 704, "01", "CLARO GTM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GTM", 704, "03", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GUF", 340, "02", "ONLY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GUM", 310, "370", "USA DOCOMO PACIFIC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GUM", 310, "140", "GTA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GUM", 310, "400", "USA_iCAN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GUY", 738, "002", "GUY CLNK PLS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("GUY", 738, "01", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "12", "China Mobile HK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "13", "China Mobile HK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "18", "CSL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "02", "CSL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "10", "CSL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "00", "CSL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "16", "PCCW-HKT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "19", "PCCW-HKT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "20", "PCCW-HKT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "04", "3(2G)");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "03", "3");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "17", "SmarTone HK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "15", "SmarTone HK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HKG", 454, "06", "SmarTone HK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HND", 708, "030", "HND");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HND", 708, "001", "CLARO HND");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HND", 708, "02", "CELTELHND");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HRV", 219, "02", "Tele2 HR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HRV", 219, "10", "HR VIP");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HTI", 372, "03", "Natcom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HUN", 216, "30", "Telekom HU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HUN", 216, "01", "Telenor HU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("HUN", 216, "70", "vodafone HU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IDN", 510, "00", "ACeS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IDN", 510, "89", "3");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IDN", 510, "01", "IND INDOSAT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IDN", 510, "21", "IND INDOSAT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IDN", 510, "10", "IND TELKOMSEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IDN", 510, "08", "AXIS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "42", "AIRCEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "801", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "800", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "806", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "802", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "804", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "803", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "805", "Aircel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "79", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "73", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "38", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "75", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "64", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "57", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "34", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "51", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "62", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "71", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "72", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "81", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "58", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "66", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "77", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "76", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "53", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "59", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "80", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "55", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "54", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "74", "CellOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "52", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "97", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "49", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "51", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "56", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "94", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "93", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "90", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "95", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "96", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "54", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "55", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "53", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "45", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "40", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "02", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "10", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "03", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "98", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "92", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "31", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "16", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "70", "IND airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "82", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "19", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "799", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "853", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "04", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "14", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "89", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "12", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "87", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "56", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "852", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "848", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "07", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "846", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "845", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "44", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "24", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "78", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "849", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "850", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "70", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "22", "IDEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "68", "IN-DOLPHIN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "69", "IN-DOLPHIN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "09", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "36", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "50", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "52", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "18", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "85", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "67", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "83", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "20", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "19", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "21", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "15", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "13", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "11", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "22", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "01", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "09", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "07", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "06", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "05", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "10", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "18", "Reliance");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "858", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "866", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "855", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "854", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "859", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "860", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "861", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "863", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "864", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "865", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "840", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "856", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "862", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "870", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "873", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "871", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "869", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "868", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "857", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "874", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "867", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "872", "IND-JIO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "027", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "043", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "042", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "041", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "044", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "045", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "047", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "046", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "036", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "038", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "030", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "029", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "025", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "031", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "032", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "035", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "034", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "037", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "039", "TATA DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "819", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "818", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "876", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "875", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "879", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "927", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "929", "IN UNITECH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "831", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "833", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "832", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "830", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "827", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "824", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "825", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "828", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "829", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "834", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "835", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "843", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "823", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "841", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "842", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "839", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "837", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "836", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "838", "VIDEOCON");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "13", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "84", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "11", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "05", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "01", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "86", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "46", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "030", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "27", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "20", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "88", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "60", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "43", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 404, "15", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "66", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "67", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "751", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "752", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "754", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "750", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "756", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "755", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IND", 405, "753", "Vodafone IN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRL", 272, "05", "3 IRL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRL", 272, "03", "IRL - METEOR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRL", 272, "02", "O2-IRL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRL", 272, "01", "vodafone IE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRN", 432, "35", "MTN Irancell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRN", 432, "14", "IR KISH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRN", 432, "11", "IR-TCI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRN", 432, "32", "Iran Taliya");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRN", 432, "20", "IRN 20");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRQ", 418, "05", "ASIACELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRQ", 418, "30", "IRAQNA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRQ", 418, "20", "zain IQ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("IRQ", 418, "40", "KOREK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISL", 274, "02", "Vodafone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISL", 274, "04", "Viking");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISL", 274, "11", "NOVA IS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISL", 274, "08", "On-waves");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISL", 274, "01", "Siminn");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISL", 274, "12", "Siminn");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISR", 425, "02", "Cellcom IL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISR", 425, "01", "Orange IL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ISR", 425, "03", "IL Pelephone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ITA", 222, "99", "3 ITA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ITA", 222, "01", "I TIM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ITA", 901, "26", "TIM@sea");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ITA", 222, "10", "vodafone IT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ITA", 222, "88", "I WIND");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JAM", 338, "180", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JAM", 338, "050", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JEY", 234, "03", "Airtel-Vodafone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JOR", 416, "01", "Zain JO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JOR", 416, "77", "Orange");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JOR", 416, "03", "UMNIAH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JPN", 440, "50", "KDDI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JPN", 440, "10", "JP DOCOMO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JPN", 440, "20", "SoftBank");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("JPN", 440, "00", "Ymobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KAZ", 401, "07", "ALTEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KAZ", 401, "01", "Beeline KZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KAZ", 401, "02", "KZ KCELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KAZ", 401, "77", "Tele2");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KEN", 639, "03", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KEN", 639, "02", "Safaricom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KEN", 639, "07", "GSM Telkom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "01", "Cellcard");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "04", "CADCOMMS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "05", "SMART");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "06", "SMART");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "18", "Mfone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "09", "Beeline KH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "11", "SEATEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KHM", 456, "08", "Metfone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KNA", 356, "110", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KOR", 467, "05", "Koryolink");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KOR", 450, "08", "KT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KOR", 450, "02", "KT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KOR", 450, "06", "KOR LG Uplus");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KOR", 450, "05", "KOR SK Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KWT", 419, "04", "KT, VIVA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KWT", 419, "02", "Zain KW");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("KWT", 419, "03", "Ooredoo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LAO", 457, "02", "ETL MOBILE NETWORK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LAO", 457, "01", "LAO GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LAO", 457, "03", "Unitel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LAO", 457, "08", "TIGO LAO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBN", 415, "01", "alfa");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBN", 415, "05", "LBN OGERO Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBR", 618, "07", "Celcom GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBR", 618, "01", "LBR Lonestar Cell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBR", 618, "04", "Novafone 4G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBY", 606, "01", "Al Madar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LBY", 606, "00", "Libyana");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LCA", 358, "110", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LCA", 358, "050", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LIE", 295, "05", "FL1");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LIE", 295, "02", "Orange FL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LIE", 295, "01", "SwisscomFL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LKA", 413, "05", "SRI AIRTEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LKA", 413, "02", "DIALOG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LKA", 413, "08", "Hutch");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LKA", 413, "01", "Mobitel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LSO", 651, "02", "LS-ETL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LTU", 246, "01", "OMNITEL LT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LTU", 246, "02", "LT BITE GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LTU", 246, "03", "Tele2 LT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LUX", 270, "01", "POST");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LUX", 270, "99", "L Orange-LU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LUX", 270, "77", "L TANGO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LVA", 247, "01", "LV LMT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LVA", 247, "05", "BITE LV");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("LVA", 247, "02", "Tele2 LV");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MAC", 455, "03", "3 Macau");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MAC", 455, "00", "SmarTone MAC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MCO", 212, "01", "vala");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MCO", 212, "10", "Monaco");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDA", 259, "05", "UNITE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDA", 259, "01", "Orange MD");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDG", 646, "01", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDG", 646, "02", "Orange MG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDG", 646, "04", "TELMA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDV", 472, "01", "DHIRAAGU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MDV", 472, "02", "Ooredoo Maldives PVT LTD");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MEX", 334, "50", "Iusacell 4G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MEX", 334, "050", "Iusacell 4G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MEX", 334, "090", "Nextel 3G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MEX", 334, "03", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MEX", 334, "020", "TELCEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MKD", 294, "02", "ONE MK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MKD", 294, "01", "T-Mobile MK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MKD", 294, "03", "Vip MKD");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MLI", 610, "01", "MALITEL ML");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MLI", 610, "02", "ORANGE ML");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MLT", 278, "77", "Telecoms Malta");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MLT", 278, "21", "go mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MLT", 278, "01", "vodafone MT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MMR", 414, "01", "MM 900");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MMR", 414, "05", "Ooredoo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MNE", 297, "02", "Telekom.me");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MNE", 297, "01", "Telenor");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MNG", 428, "06", "GMOBILE_MN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MNG", 428, "99", "MN MobiCom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MNG", 428, "01", "Skytel MN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MNG", 428, "88", "MONGOLIA UNITEL LLC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MOR", 604, "01", "MOR IAM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MOR", 604, "00", "MOR MEDITEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MOZ", 643, "01", "MOZ - mCel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MOZ", 643, "03", "MOVITEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MOZ", 643, "04", "VodaCom-MZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MRT", 609, "02", "MR Expresso");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MRT", 609, "01", "MR MATTEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MRT", 609, "10", "MAURITEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MRU", 617, "01", "CELLPLUS-MRU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MRU", 617, "10", "EMTEL-MRU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MSR", 354, "860", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MUS", 617, "03", "MTML");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MWI", 650, "10", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MWI", 650, "01", "TNM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MYS", 502, "156", "MYSALTEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MYS", 502, "19", "MY CELCOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MYS", 502, "13", "MY CELCOM 3G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MYS", 502, "16", "DiGi");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MYS", 502, "12", "MY MAXIS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("MYS", 502, "18", "U MOBILE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("Mar", 604, "02", "inwi");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NAM", 649, "01", "MTC NAMIBIA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NAM", 649, "03", "tnmobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NCL", 546, "01", "NCL MOBILIS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NER", 614, "02", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NER", 614, "03", "ETISALAT NER");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NFK", 505, "10", "Norfolk Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NGA", 621, "20", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NGA", 621, "60", "Etisalat Nigeria");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NGA", 621, "50", "Glo NG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NGA", 621, "30", "MTN - NG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NIC", 710, "73", "CLARO NIC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NIC", 710, "21", "CLARO NIC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NIC", 710, "300", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NLD", 204, "08", "NL KPN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NLD", 204, "12", "NL Telfort");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NLD", 204, "02", "Tele2 NL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NLD", 204, "04", "vodafone NL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NOR", 242, "04", "Mobile Norway");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NOR", 242, "05", "Mobile Norway");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NOR", 242, "01", "N Telenor");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NOR", 242, "02", "N NetCom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NPL", 429, "02", "Ncell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NZL", 530, "05", "Spark NZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NZL", 530, "24", "2degrees");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("NZL", 530, "01", "vodafone NZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("OMN", 422, "02", "Omantel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("OMN", 422, "03", "nawras");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAK", 410, "04", "ZONG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAK", 410, "03", "PK-UFONE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAK", 410, "06", "Telenor PK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAK", 410, "07", "WaridTel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAN", 714, "01", "+Movil - C&W PAN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAN", 714, "03", "CLARO PA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAN", 714, "04", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PAN", 714, "020", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PER", 716, "10", "CLARO PER");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PER", 716, "17", "PERN3");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PER", 716, "06", "MOVISTAR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PER", 716, "15", "Viettel Peru");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PHL", 515, "11", "ACeS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PHL", 515, "05", "PH Sun Cellular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PHL", 515, "02", "Globe Telecom-PH");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PHL", 515, "03", "SMART");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PLW", 552, "80", "PLWPMC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PLW", 552, "01", "PalauCel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PNG", 537, "01", "bmobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PNG", 537, "03", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("POL", 260, "06", "Play");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("POL", 260, "03", "Orange PL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("POL", 260, "01", "Plus");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("POL", 260, "02", "T-Mobile.pl");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRI", 330, "120", "Open Mob PRI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRI", 330, "110", "PR Claro");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRT", 268, "06", "MEO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRT", 268, "03", "NOS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRT", 268, "01", "vodafone P");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRY", 744, "02", "CLARO PY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRY", 744, "01", "HOLA PARAGUAY S.A.");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRY", 744, "05", "PY Personal");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PRY", 744, "04", "TIGO PY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PSE", 425, "05", "JAWWAL-PALESTINE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PSE", 425, "06", "PS, Wataniya Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PYF", 547, "15", "Vodafone PF");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("PYF", 547, "20", "F-VINI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("QAT", 427, "01", "Ooredoo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("QAT", 427, "02", "vodafone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("REU", 647, "02", "ONLY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("REU", 647, "00", "Orange re");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RMI", 551, "01", "MH-NTA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ROU", 226, "10", "RO ORANGE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ROU", 226, "05", "RO Digi.Mobil");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ROU", 226, "03", "TELEKOM.RO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ROU", 226, "01", "RO Vodafone RO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "12", "ROSTELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "05", "ROSTELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "35", "MOTIV");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "01", "MTS RUS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "03", "ROSTELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "02", "MegaFon RUS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "17", "ROSTELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "38", "ROSTELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "39", "ROSTELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "99", "Beeline");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "16", "NTC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "07", "RUS 07, RUS SMARTS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "15", "RUS15, RUS SMARTS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RUS", 250, "20", "TELE2 RU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RWA", 635, "14", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("RWA", 635, "13", "TIGO RWANDA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SAU", 420, "03", "Mobily-KSA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SAU", 420, "04", "Zain KSA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SAU", 420, "01", "STC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SDN", 634, "02", "MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SDN", 634, "01", "Zain SDN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SEN", 608, "02", "SN-SENTEL SG");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SEN", 608, "01", "SN ALIZE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SEN", 608, "03", "SEN expresso");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SGP", 525, "03", "SGP-M1");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SGP", 525, "01", "Singtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SGP", 525, "02", "Singtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SGP", 525, "07", "SGP Call Zone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SGP", 525, "05", "StarHub");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLB", 540, "02", "bmobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLE", 619, "01", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLE", 619, "05", "Africell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLV", 706, "01", "CLARO SLV");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLV", 706, "02", "Digicel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLV", 706, "04", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SLV", 706, "03", "TELEMOVIL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SMR", 292, "01", "SMT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SOM", 637, "30", "Som Golis");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SOM", 637, "04", "SOMAFONE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SOM", 637, "20", "Somnet TELECOM Inc");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SOM", 637, "01", "SO Telesom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SPM", 308, "01", "SPM AMERIS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SRB", 220, "03", "mt:s");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SRB", 220, "01", "Telenor SRB");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SRB", 220, "05", "Vip SRB");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SRI", 413, "03", "SRI Etisalat");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SSD", 659, "03", "Gemtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SSD", 659, "02", "MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SSD", 659, "04", "Vivacell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SSD", 659, "06", "ZAIN SS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("STP", 626, "01", "STP CSTmovel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("STP", 626, "02", "Unitel STP");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SUR", 746, "03", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SUR", 746, "04", "UNIQA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SUR", 746, "02", "SR.TELESUR.GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVK", 231, "06", "O2 - SK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVK", 231, "01", "Orange SK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVK", 231, "02", "Telekom SK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVN", 293, "40", "Si.mobil");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVN", 293, "64", "T-2");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVN", 293, "41", "MOBITEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SVN", 293, "70", "SI TUSMOBIL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "02", "3 SE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "07", "Tele2");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "24", "Sweden Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "08", "Telenor SE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "04", "SWEDEN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "01", "TELIA S");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWE", 240, "05", "Sweden 3G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SWZ", 653, "10", "Swazi-MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SYC", 633, "10", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SYC", 633, "01", "C&W SEY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SYR", 417, "02", "MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("SYR", 417, "01", "SYRIATEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TCA", 376, "350", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TCA", 376, "360", "IslandCom TCI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TCD", 622, "01", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TCD", 622, "03", "Tigo TD");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TCD", 622, "07", "SALAM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TGO", 615, "03", "ETISALAT TOGO");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TGO", 615, "01", "TG-TOGO CELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "20", "ACeS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "01", "TH GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "03", "AIS 3G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "00", "TH 3G+");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "05", "dtac TriNet");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "23", "TH GSM 1800");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "15", "TOT3G");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "18", "TH-DTAC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "99", "TRUE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("THA", 520, "04", "TRUE 3G+");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TJK", 436, "04", "Babilon-M");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TJK", 436, "01", "TCELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TJK", 436, "02", "TCELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TJK", 436, "03", "MegaFon TJK");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TJK", 436, "05", "BEELINE TJ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TKM", 438, "02", "TM CELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TKM", 438, "01", "MTS TM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TLS", 514, "02", "TLS-TT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TON", 539, "88", "Digicel Tonga");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TON", 539, "01", "U-CALL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TTO", 374, "12", "TSTT");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TUN", 605, "01", "Orange");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TUN", 605, "03", "TUNISIANA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TUN", 605, "02", "TUNISIE TELECOM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TUR", 286, "03", "AVEA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TUR", 286, "01", "TR TURKCELL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TUR", 286, "02", "VODAFONE TR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "68", "ACeS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "92", "Chunghwa Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "88", "KGT-Online");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "01", "Far EasTone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "93", "TWN MOBITAI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "97", "TW Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TWN", 466, "89", "T Star");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TZA", 640, "05", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TZA", 640, "02", "TIGO - TZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TZA", 640, "04", "VodaCom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TZA", 640, "03", "ZANTEL-TZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UGA", 641, "14", "ORANGE UGANDA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UGA", 641, "22", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UGA", 641, "01", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UGA", 641, "10", "MTN-UGANDA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UGA", 641, "18", "Suretelcom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UGA", 641, "11", "Uganda Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UKR", 255, "06", "life:)");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UKR", 255, "02", "Beeline UA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UKR", 255, "03", "UA-KYIVSTAR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UKR", 255, "01", "MTS UKR");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UKR", 255, "07", "TriMob");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("URY", 748, "10", "CLARO URUGUAY");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("URY", 748, "01", "Antel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("URY", 748, "07", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "150", "AT&T");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "380", "AT&T");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "170", "AT&T");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "410", "AT&T");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "030", "AT&T");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "280", "AT&T");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "880", "USAACSI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "640", "USA AE Airadigm");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "710", "USA ASTAC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "810", "Bluegrass Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "180", "West Central Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "500", "MOSAIC");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "190", "USAC1ECI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "630", "USA AmeriLink");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "420", "Cinti Bell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "040", "USA - Commnet");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "240", "USACWCI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "080", "Corr Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "032", "IT&E");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "030", "Indigo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "530", "Iowa Wireless USA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "770", "Iowa Wireless USA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "650", "Jasper");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "870", "US");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "690", "Limitless Mobile USA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "090", "USASXLP");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "570", "Chinook");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "330", "BTW");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "290", "NEP Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 312, "630", "NetGenuity");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "530", "USANW");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 312, "260", "USACL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "460", "USA1L");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 312, "230", "SRT Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "450", "Cell One of NE Colorado");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "710", "Northeast Wireless");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "740", "USA OTZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "080", "Pine Cellular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "730", "USA Proximiti");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "540", "USA Proximiti");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 312, "480", "Sagebrush");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "320", "USA - CellularOne");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "120", "Sprint");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "490", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "660", "Metro PCS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "310", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "210", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "200", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "160", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "240", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "250", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "270", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "260", "T-Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "840", "telna Mobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "100", "US PLATEAU");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "50", "ACS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "190", "USA Dutch Harbor");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "370", "GCI");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "020", "US - Union Telephone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "730", "U.S.Cellular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "580", "U.S.Cellular");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 312, "060", "CoverageCo");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "890", "Verizon");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "480", "Verizon");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "590", "Verizon");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "340", "WestLink");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 311, "150", "Wilkes USA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("USA", 310, "300", "BigSkyUS");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UZB", 434, "05", "UZB Ucell");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UZB", 434, "04", "Beeline UZ");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("UZB", 434, "07", "UMS-UZB");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VCT", 360, "110", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VCT", 360, "070", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VEN", 734, "02", "DIGITEL GSM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VEN", 734, "04", "Movistar");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VEN", 734, "06", "VE_MOVILNET");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VGB", 348, "170", "LIME");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VGB", 348, "570", "CCT Boatphone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VNM", 452, "07", "Gmobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VNM", 452, "05", "VN Vietnamobile");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VNM", 452, "01", "VN Mobifone");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VNM", 452, "02", "VN VINAPHONE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VNM", 452, "04", "VIETTEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VUT", 541, "05", "Digicel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("VUT", 541, "01", "VUT SMILE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("WSM", 549, "27", "Bluesky");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("WSM", 549, "00", "DIGICEL");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("YEM", 421, "02", "MTN");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("YEM", 421, "04", "Y-Telecom");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("YEM", 421, "01", "SabaFon");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZAF", 655, "07", "Cell C");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZAF", 655, "10", "MTN-SA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZAF", 655, "02", "TelkomSA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZAF", 655, "01", "VodaCom-SA");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZMB", 645, "01", "Airtel");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZMB", 645, "02", "MTN ZM");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZWE", 648, "04", "ZW ECONET");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZWE", 648, "01", "ZW NET*ONE");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("ZWE", 648, "03", "TELECEL ZW");
insert into mcc_mnc_oper_list (country, mcc, mnc, oper)  values ("TBD", 450, "01", "Samsung Test Bed");
COMMIT;
